name: IBShulker
version: '${project.version}'
main: ibotus.ibshulker.Main
api-version: '1.16'
authors: [IBoTuS]
permissions:
  ibshulker.bypass:
    description: Allows you to use the Ender Chest and place items inside