name: IBShulker
version: '1.1+'
main: ibotus.ibshulker.Main
api-version: '1.20'
authors: [IBoTuS,Vinely]
permissions:
  ibshulker.bypass:
    description: Allows you to use the Ender Chest and place items inside